(function(){'use strict';
var KEY='hdb_control_state_v11';
var seed={
 rooms:[
  {id:'R-1201',number:'1201',floor:'12',guest:'أحمد محمد',status:'occupied',tv:'online',updated:'منذ دقيقتين'},
  {id:'R-1202',number:'1202',floor:'12',guest:'—',status:'vacant',tv:'online',updated:'منذ 5 دقائق'},
  {id:'R-1203',number:'1203',floor:'12',guest:'سارة خالد',status:'occupied',tv:'online',updated:'الآن'},
  {id:'R-1204',number:'1204',floor:'12',guest:'—',status:'service',tv:'offline',updated:'منذ 17 دقيقة'},
  {id:'R-1301',number:'1301',floor:'13',guest:'محمد علي',status:'occupied',tv:'online',updated:'منذ 4 دقائق'},
  {id:'R-1302',number:'1302',floor:'13',guest:'—',status:'vacant',tv:'online',updated:'منذ 11 دقيقة'},
  {id:'R-1303',number:'1303',floor:'13',guest:'عبدالله سالم',status:'occupied',tv:'online',updated:'منذ دقيقة'},
  {id:'R-1401',number:'1401',floor:'14',guest:'—',status:'vacant',tv:'online',updated:'منذ 8 دقائق'}
 ],
 devices:[
  {id:'TV-1201',room:'1201',brand:'Samsung',model:'Q155Q7F',ip:'192.168.20.31',status:'online',version:'Tizen 9.0',last:'الآن'},
  {id:'TV-1202',room:'1202',brand:'Samsung',model:'Q155Q7F',ip:'192.168.20.32',status:'online',version:'Tizen 9.0',last:'منذ 3 دقائق'},
  {id:'TV-1204',room:'1204',brand:'LG',model:'UT801C',ip:'192.168.20.34',status:'offline',version:'webOS',last:'منذ 17 دقيقة'},
  {id:'TV-1301',room:'1301',brand:'LG',model:'UT801C',ip:'192.168.20.41',status:'online',version:'webOS',last:'منذ دقيقة'}
 ],
 channels:[
  {id:'CH-1',number:1,name:'القرآن الكريم',group:'القرآن',source:'udp://239.10.1.1:5000',quality:'1080p',status:'online'},
  {id:'CH-2',number:2,name:'السنة النبوية',group:'السعودية',source:'udp://239.10.1.2:5000',quality:'1080p',status:'online'},
  {id:'CH-3',number:3,name:'السعودية',group:'السعودية',source:'udp://239.10.1.3:5000',quality:'1080p',status:'online'},
  {id:'CH-4',number:4,name:'الإخبارية',group:'الأخبار',source:'udp://239.10.1.4:5000',quality:'1080p',status:'online'},
  {id:'CH-5',number:5,name:'MBC 1',group:'الترفيه',source:'udp://239.10.2.1:5000',quality:'1080p',status:'online'},
  {id:'CH-6',number:6,name:'MBC Action',group:'الترفيه',source:'udp://239.10.2.2:5000',quality:'720p',status:'warning'}
 ],
 requests:[
  {id:'REQ-1042',name:'مستلزمات إضافية',room:'1203',status:'new',time:'07:18'},
  {id:'REQ-1041',name:'تنظيف الغرفة',room:'1301',status:'progress',time:'07:11'},
  {id:'REQ-1040',name:'صيانة التكييف',room:'1204',status:'progress',time:'06:56'},
  {id:'REQ-1039',name:'حمل الأمتعة',room:'1402',status:'done',time:'06:42'}
 ],
 messages:[
  {id:'MSG-1',title:'مرحبًا بك في هدب',target:'كل الفندق',status:'published',date:'اليوم 06:30'},
  {id:'MSG-2',title:'عرض المطعم',target:'الغرف المشغولة',status:'published',date:'أمس 18:20'}
 ],
 audit:[
  {title:'تم تحديث ترتيب القنوات',user:'مدير النظام',time:'منذ 12 دقيقة'},
  {title:'تم ربط التلفزيون TV-1301',user:'قسم التقنية',time:'منذ 28 دقيقة'},
  {title:'تم تسكين الغرفة 1203',user:'الاستقبال',time:'منذ 45 دقيقة'}
 ],
 experience:{hotel:'HDB Hospitality',title:'أهلًا بك في هدب',subtitle:'إقامة هادئة وتجربة رقمية صُممت لتكون كل خدمات الفندق بين يديك.',color:'#d6b36a'}
};
var state=load();var currentView='dashboard';
function $(s,r){return(r||document).querySelector(s)}function $$(s,r){return[].slice.call((r||document).querySelectorAll(s))}
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');return x||clone(seed)}catch(e){return clone(seed)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){} }
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function labelStatus(s){return{occupied:'مشغولة',vacant:'شاغرة',service:'خدمة',online:'متصل',offline:'غير متصل',warning:'تنبيه',new:'جديد',progress:'قيد التنفيذ',done:'مكتمل',published:'منشورة'}[s]||s}
function toast(text){var el=$('#toast');if(!el)return;el.textContent=text;el.classList.add('show');setTimeout(function(){el.classList.remove('show')},2200)}
function audit(title,user){state.audit.unshift({title:title,user:user||'مدير النظام',time:'الآن'});state.audit=state.audit.slice(0,20);save()}
function metric(title,value,sub,icon){return'<article class="metric"><div class="metric-top"><span>'+esc(title)+'</span><span class="metric-icon">'+icon+'</span></div><strong>'+esc(value)+'</strong><small>'+esc(sub)+'</small></article>'}
function renderMetrics(){var occupied=state.rooms.filter(function(x){return x.status==='occupied'}).length;var online=state.devices.filter(function(x){return x.status==='online'}).length;var active=state.channels.filter(function(x){return x.status==='online'}).length;var open=state.requests.filter(function(x){return x.status!=='done'}).length;$('#metrics').innerHTML=metric('الغرف المشغولة',occupied+'/'+state.rooms.length,'نسبة الإشغال الحالية','▦')+metric('التلفزيونات المتصلة',online+'/'+state.devices.length,'أجهزة نشطة الآن','▣')+metric('القنوات العاملة',active+'/'+state.channels.length,'مصادر بث مستقرة','▶')+metric('طلبات مفتوحة',open,'تحتاج متابعة','◇')}
function renderRoomMap(){var el=$('#room-map');if(!el)return;el.innerHTML=state.rooms.map(function(r){return'<div class="room-cell '+r.status+'"><strong>'+esc(r.number)+'</strong><span>'+esc(labelStatus(r.status))+' · '+esc(r.tv==='online'?'TV متصل':'TV متوقف')+'</span></div>'}).join('')}
function renderHealth(){var items=[['WISI Headend','Tangram / OM','98%'],['IPTV Middleware','API & Sessions','96%'],['FFmpeg Relay','12 Streams','92%'],['PMS Connector','Ready for setup','84%']];$('#health-list').innerHTML=items.map(function(x){return'<div class="health-row"><div><strong>'+x[0]+'</strong><small>'+x[1]+'</small></div><div class="health-bar"><i style="width:'+x[2]+'"></i></div></div>'}).join('')}
function renderRequestsTable(){var el=$('#request-table');if(!el)return;el.innerHTML=state.requests.slice(0,5).map(function(r){return'<tr><td>'+esc(r.name)+'</td><td>'+esc(r.room)+'</td><td><span class="state '+r.status+'">'+labelStatus(r.status)+'</span></td><td>'+esc(r.time)+'</td></tr>'}).join('')}
function renderStreams(){var el=$('#stream-list');if(!el)return;el.innerHTML=state.channels.slice(0,5).map(function(c){return'<div class="stream-row"><div><strong>'+esc(c.name)+'</strong><small>'+esc(c.quality)+' · '+esc(c.source)+'</small></div><span class="stream-signal">'+(c.status==='online'?'● LIVE':'▲ CHECK')+'</span></div>'}).join('')}
function renderDashboard(){renderMetrics();renderRoomMap();renderHealth();renderRequestsTable();renderStreams()}
function roomRow(r){return'<tr><td><strong>'+esc(r.number)+'</strong></td><td>'+esc(r.floor)+'</td><td>'+esc(r.guest)+'</td><td><span class="state '+r.status+'">'+labelStatus(r.status)+'</span></td><td><span class="state '+r.tv+'">'+labelStatus(r.tv)+'</span></td><td>'+esc(r.updated)+'</td><td><div class="row-actions"><button class="icon-btn" data-edit-room="'+esc(r.id)+'">✎</button><button class="icon-btn" data-delete-room="'+esc(r.id)+'">×</button></div></td></tr>'}
function renderRooms(){var q=($('#room-search').value||'').trim().toLowerCase();var f=$('#room-filter').value;var rows=state.rooms.filter(function(r){return(!q||[r.number,r.floor,r.guest].join(' ').toLowerCase().indexOf(q)>-1)&&(f==='all'||r.status===f)});$('#rooms-table').innerHTML=rows.map(roomRow).join('')||'<tr><td colspan="7">لا توجد نتائج</td></tr>'}
function renderDevices(){var q=($('#device-search').value||'').trim().toLowerCase();var data=state.devices.filter(function(d){return!q||[d.id,d.room,d.brand,d.model,d.ip].join(' ').toLowerCase().indexOf(q)>-1});$('#devices-grid').innerHTML=data.map(function(d){return'<article class="device-card"><div class="device-head"><div class="device-icon">▣</div><span class="state '+d.status+'">'+labelStatus(d.status)+'</span></div><h3>'+esc(d.brand+' '+d.model)+'</h3><p>الغرفة '+esc(d.room)+' · '+esc(d.ip)+'</p><div class="device-stats"><div><span>النظام</span><strong>'+esc(d.version)+'</strong></div><div><span>آخر ظهور</span><strong>'+esc(d.last)+'</strong></div></div><div class="row-actions" style="margin-top:13px"><button class="btn ghost" data-device-command="restart" data-id="'+esc(d.id)+'">إعادة تشغيل</button><button class="btn ghost" data-delete-device="'+esc(d.id)+'">حذف</button></div></article>'}).join('')||'<div class="panel">لا توجد أجهزة</div>'}
function channelRow(c){return'<tr><td>'+esc(c.number)+'</td><td><strong>'+esc(c.name)+'</strong></td><td>'+esc(c.group)+'</td><td>'+esc(c.source)+'</td><td>'+esc(c.quality)+'</td><td><span class="state '+(c.status==='warning'?'service':c.status)+'">'+labelStatus(c.status)+'</span></td><td><div class="row-actions"><button class="icon-btn" data-edit-channel="'+esc(c.id)+'">✎</button><button class="icon-btn" data-delete-channel="'+esc(c.id)+'">×</button></div></td></tr>'}
function renderChannels(){var q=($('#channel-search').value||'').trim().toLowerCase();var data=state.channels.filter(function(c){return!q||[c.name,c.group,c.source,c.number].join(' ').toLowerCase().indexOf(q)>-1});data.sort(function(a,b){return Number(a.number)-Number(b.number)});$('#channels-table').innerHTML=data.map(channelRow).join('')}
function renderServiceMetrics(){var all=state.requests.length,n=state.requests.filter(function(x){return x.status==='new'}).length,p=state.requests.filter(function(x){return x.status==='progress'}).length;$('#service-metrics').innerHTML=metric('إجمالي اليوم',all,'كل طلبات النزلاء','◇')+metric('طلبات جديدة',n,'بانتظار التوجيه','!')+metric('قيد التنفيذ',p,'تتم متابعتها الآن','↻')}
function requestAction(r){if(r.status==='new')return'<button class="btn primary" data-next-request="'+r.id+'">بدء التنفيذ</button>';if(r.status==='progress')return'<button class="btn primary" data-next-request="'+r.id+'">إكمال</button>';return'<span class="status good">مغلق</span>'}
function renderServices(){renderServiceMetrics();var f=$('#request-filter').value;var data=state.requests.filter(function(r){return f==='all'||r.status===f});$('#services-table').innerHTML=data.map(function(r){return'<tr><td>'+esc(r.id)+'</td><td><strong>'+esc(r.name)+'</strong></td><td>'+esc(r.room)+'</td><td><span class="state '+r.status+'">'+labelStatus(r.status)+'</span></td><td>'+esc(r.time)+'</td><td>'+requestAction(r)+'</td></tr>'}).join('')}
function renderMessages(){var el=$('#message-list');if(!el)return;el.innerHTML=state.messages.map(function(m){return'<div class="message-row"><div><strong>'+esc(m.title)+'</strong><small>'+esc(m.target)+' · '+esc(m.date)+'</small></div><div class="row-actions"><span class="status good">منشورة</span><button class="icon-btn" data-delete-message="'+esc(m.id)+'">×</button></div></div>'}).join('')}
function renderExperience(){var e=state.experience;$('#experience-hotel').value=e.hotel;$('#experience-title').value=e.title;$('#experience-subtitle').value=e.subtitle;$('#experience-color').value=e.color;updatePreview()}
function updatePreview(){var title=$('#experience-title').value||'أهلًا بك';var sub=$('#experience-subtitle').value||'';var color=$('#experience-color').value||'#d6b36a';$('#preview-title').textContent=title;$('#preview-subtitle').textContent=sub;document.documentElement.style.setProperty('--gold',color)}
function renderSystem(){var online=state.devices.filter(function(x){return x.status==='online'}).length;$('#system-metrics').innerHTML=metric('زمن التشغيل','14 يوم','بدون انقطاع','↑')+metric('جلسات التلفزيون',online,'أجهزة متصلة الآن','▣')+metric('استخدام التخزين','34%','مساحة متاحة','◫')+metric('آخر نسخة احتياطية','06:00','تمت بنجاح','✓');var services=[['Web Server','Apache / PHP','online'],['Hotel API','JSON REST','online'],['Channel Scanner','آخر فحص: 07:15','online'],['PMS Connector','غير مربوط','offline'],['Casting Gateway','غير مفعل','offline']];$('#system-services').innerHTML=services.map(function(s){return'<div class="health-row"><div><strong>'+s[0]+'</strong><small>'+s[1]+'</small></div><span class="state '+s[2]+'">'+labelStatus(s[2])+'</span></div>'}).join('');$('#audit-list').innerHTML=state.audit.map(function(a){return'<div class="audit-row"><div><strong>'+esc(a.title)+'</strong><small>'+esc(a.user)+'</small></div><small>'+esc(a.time)+'</small></div>'}).join('')}
function renderAll(){renderDashboard();renderRooms();renderDevices();renderChannels();renderServices();renderMessages();renderExperience();renderSystem()}
var titles={dashboard:['OVERVIEW','مركز القيادة','إضافة غرفة'],rooms:['ROOM OPERATIONS','الغرف والإقامات','إضافة غرفة'],devices:['DEVICE FLEET','التلفزيونات والأجهزة','ربط تلفزيون'],channels:['CONTENT & STREAMS','القنوات والباقات','إضافة قناة'],services:['GUEST REQUESTS','الخدمات والطلبات','طلب جديد'],messages:['MESSAGING','الرسائل والعروض','رسالة جديدة'],experience:['GUEST EXPERIENCE','تجربة النزيل','نشر التصميم'],system:['SYSTEM HEALTH','حالة النظام','نسخة احتياطية']};
function showView(name){currentView=name;$$('.view').forEach(function(x){x.classList.remove('active')});$$('.nav-item').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-view')===name)});var v=$('#view-'+name);if(v)v.classList.add('active');var t=titles[name]||titles.dashboard;$('#view-kicker').textContent=t[0];$('#view-title').textContent=t[1];$('#primary-btn').textContent=t[2];renderAll()}
function fieldsFor(type,obj){obj=obj||{};if(type==='room')return[{n:'number',l:'رقم الغرفة',v:obj.number||''},{n:'floor',l:'الدور',v:obj.floor||''},{n:'guest',l:'اسم النزيل',v:obj.guest||'—'},{n:'status',l:'الحالة',type:'select',opts:[['occupied','مشغولة'],['vacant','شاغرة'],['service','خدمة']],v:obj.status||'vacant'}];if(type==='device')return[{n:'room',l:'رقم الغرفة',v:''},{n:'brand',l:'الشركة',type:'select',opts:[['Samsung','Samsung'],['LG','LG'],['STB','STB']],v:'Samsung'},{n:'model',l:'الموديل',v:''},{n:'ip',l:'عنوان IP',v:''}];if(type==='channel')return[{n:'number',l:'رقم القناة',v:obj.number||state.channels.length+1},{n:'name',l:'اسم القناة',v:obj.name||''},{n:'group',l:'المجموعة',v:obj.group||''},{n:'source',l:'رابط المصدر',v:obj.source||''},{n:'quality',l:'الجودة',type:'select',opts:[['1080p','1080p'],['720p','720p'],['SD','SD']],v:obj.quality||'1080p'}];return[]}
var modalContext=null;
function openModal(type,obj){modalContext={type:type,obj:obj||null};var names={room:'غرفة',device:'تلفزيون',channel:'قناة'};$('#modal-title').textContent=(obj?'تعديل ':'إضافة ')+(names[type]||'عنصر');$('#modal-kicker').textContent=obj?'UPDATE':'CREATE';var fields=fieldsFor(type,obj);$('#modal-fields').innerHTML=fields.map(function(f){var input;if(f.type==='select')input='<select name="'+f.n+'">'+f.opts.map(function(o){return'<option value="'+o[0]+'" '+(String(o[0])===String(f.v)?'selected':'')+'>'+o[1]+'</option>'}).join('')+'</select>';else input='<input name="'+f.n+'" value="'+esc(f.v)+'" required>';return'<label>'+f.l+input+'</label>'}).join('');$('#entity-modal').showModal()}
function formData(){var out={};$$('#modal-fields [name]').forEach(function(el){out[el.name]=el.value.trim()});return out}
function saveModal(e){e.preventDefault();if(!modalContext)return;var d=formData(),t=modalContext.type,o=modalContext.obj;if(t==='room'){if(o){Object.assign(o,d,{updated:'الآن'})}else state.rooms.push({id:'R-'+Date.now(),number:d.number,floor:d.floor,guest:d.guest||'—',status:d.status,tv:'online',updated:'الآن'});audit((o?'تم تعديل الغرفة ':'تم إضافة الغرفة ')+d.number)}else if(t==='device'){state.devices.push({id:'TV-'+Date.now(),room:d.room,brand:d.brand,model:d.model,ip:d.ip,status:'online',version:d.brand==='Samsung'?'Tizen':'webOS',last:'الآن'});audit('تم ربط تلفزيون بالغرفة '+d.room)}else if(t==='channel'){if(o)Object.assign(o,d,{number:Number(d.number)});else state.channels.push({id:'CH-'+Date.now(),number:Number(d.number),name:d.name,group:d.group,source:d.source,quality:d.quality,status:'online'});audit((o?'تم تعديل قناة ':'تم إضافة قناة ')+d.name)}save();$('#entity-modal').close();renderAll();toast('تم الحفظ بنجاح')}
function deleteBy(type,id){var map={room:'rooms',device:'devices',channel:'channels',message:'messages'},key=map[type];if(!key)return;state[key]=state[key].filter(function(x){return x.id!==id});audit('تم حذف عنصر من '+key);save();renderAll();toast('تم الحذف')}
function publishMessage(){var title=$('#msg-title').value.trim(),body=$('#msg-body').value.trim(),target=$('#msg-target').value;if(!title||!body){toast('أكمل بيانات الرسالة');return}state.messages.unshift({id:'MSG-'+Date.now(),title:title,target:target,status:'published',date:'الآن'});audit('تم نشر رسالة: '+title);save();renderMessages();toast('تم نشر الرسالة')}
function publishExperience(){state.experience={hotel:$('#experience-hotel').value,title:$('#experience-title').value,subtitle:$('#experience-subtitle').value,color:$('#experience-color').value};try{localStorage.setItem('hdb_experience',JSON.stringify(state.experience))}catch(e){}audit('تم نشر تصميم تجربة النزيل');save();toast('تم نشر التصميم للفندق')}
function handleClick(e){var nav=e.target.closest('[data-view]');if(nav){showView(nav.getAttribute('data-view'));return}var jump=e.target.closest('[data-jump]');if(jump){showView(jump.getAttribute('data-jump'));return}var a=e.target.closest('[data-action]');if(a){var x=a.getAttribute('data-action');if(x==='add-room')openModal('room');if(x==='add-device')openModal('device');if(x==='add-channel')openModal('channel');if(x==='add-message')showView('messages');return}var er=e.target.closest('[data-edit-room]');if(er){openModal('room',state.rooms.find(function(x){return x.id===er.getAttribute('data-edit-room')}));return}var ec=e.target.closest('[data-edit-channel]');if(ec){openModal('channel',state.channels.find(function(x){return x.id===ec.getAttribute('data-edit-channel')}));return}var dr=e.target.closest('[data-delete-room]');if(dr){deleteBy('room',dr.getAttribute('data-delete-room'));return}var dd=e.target.closest('[data-delete-device]');if(dd){deleteBy('device',dd.getAttribute('data-delete-device'));return}var dc=e.target.closest('[data-delete-channel]');if(dc){deleteBy('channel',dc.getAttribute('data-delete-channel'));return}var dm=e.target.closest('[data-delete-message]');if(dm){deleteBy('message',dm.getAttribute('data-delete-message'));return}var nr=e.target.closest('[data-next-request]');if(nr){var r=state.requests.find(function(x){return x.id===nr.getAttribute('data-next-request')});if(r){r.status=r.status==='new'?'progress':'done';audit('تم تحديث الطلب '+r.id);save();renderServices();renderDashboard();toast('تم تحديث حالة الطلب')}return}var cmd=e.target.closest('[data-device-command]');if(cmd){toast('تم إرسال أمر إعادة التشغيل إلى '+cmd.getAttribute('data-id'));audit('إرسال أمر للجهاز '+cmd.getAttribute('data-id'));save();return}}
function primaryAction(){if(currentView==='rooms'||currentView==='dashboard')openModal('room');else if(currentView==='devices')openModal('device');else if(currentView==='channels')openModal('channel');else if(currentView==='messages')showView('messages');else if(currentView==='experience')publishExperience();else if(currentView==='system')toast('تم إنشاء نسخة احتياطية تجريبية');else toast('تم تنفيذ الإجراء')}
function bind(){document.addEventListener('click',handleClick);$('#entity-form').addEventListener('submit',saveModal);$('#primary-btn').addEventListener('click',primaryAction);$('#refresh-btn').addEventListener('click',function(){renderAll();toast('تم تحديث البيانات')});$('#room-search').addEventListener('input',renderRooms);$('#room-filter').addEventListener('change',renderRooms);$('#device-search').addEventListener('input',renderDevices);$('#channel-search').addEventListener('input',renderChannels);$('#request-filter').addEventListener('change',renderServices);$('#publish-message').addEventListener('click',publishMessage);$('#preview-experience').addEventListener('click',updatePreview);$('#publish-experience').addEventListener('click',publishExperience);['experience-title','experience-subtitle','experience-color'].forEach(function(id){$('#'+id).addEventListener('input',updatePreview)})}
function importGuestRequests(){try{var requests=JSON.parse(localStorage.getItem('hdb_requests')||'[]');requests.forEach(function(r){if(!state.requests.some(function(x){return x.id===r.id}))state.requests.unshift({id:r.id,name:r.name,room:r.room,status:r.status||'new',time:new Date(r.created_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})})});var orders=JSON.parse(localStorage.getItem('hdb_orders')||'[]');orders.forEach(function(o){if(!state.requests.some(function(x){return x.id===o.id}))state.requests.unshift({id:o.id,name:'طلب مطعم — '+o.items.length+' أصناف',room:o.room,status:o.status||'new',time:new Date(o.created_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})})});save()}catch(e){}}
function boot(){importGuestRequests();bind();renderAll();showView('dashboard')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();