(function(){
'use strict';
var API='../api/v2/index.php';
var view='command';
var state=null;
var searchTerm='';
var seed={
 meta:{version:'2.0.0-global',property:'HDB Riyadh Tower',timezone:'Asia/Riyadh',updated_at:new Date().toISOString()},
 properties:[{id:'P1',name:'HDB Riyadh Tower',city:'Riyadh',country:'Saudi Arabia',rooms:120,status:'online'}],
 buildings:[{id:'B1',property_id:'P1',name:'Tower A',floors:20,rooms:100},{id:'B2',property_id:'P1',name:'Villa Wing',floors:4,rooms:20}],
 floors:[{id:'F12',building_id:'B1',number:'12',rooms:8},{id:'F13',building_id:'B1',number:'13',rooms:8},{id:'F14',building_id:'B1',number:'14',rooms:8}],
 rooms:[
  {id:'R1201',number:'1201',floor:'12',building:'Tower A',guest:'Ahmed Mohammed',nationality:'Saudi',status:'occupied',tv:'online',stay:'21–24 Jul',package:'Premium',dnd:false},
  {id:'R1202',number:'1202',floor:'12',building:'Tower A',guest:'—',nationality:'—',status:'vacant',tv:'online',stay:'—',package:'Standard',dnd:false},
  {id:'R1203',number:'1203',floor:'12',building:'Tower A',guest:'Sara Khaled',nationality:'Kuwaiti',status:'occupied',tv:'online',stay:'20–23 Jul',package:'Premium',dnd:true},
  {id:'R1204',number:'1204',floor:'12',building:'Tower A',guest:'—',nationality:'—',status:'service',tv:'offline',stay:'—',package:'Standard',dnd:false},
  {id:'R1301',number:'1301',floor:'13',building:'Tower A',guest:'Mohammed Ali',nationality:'Egyptian',status:'occupied',tv:'online',stay:'21–26 Jul',package:'VIP',dnd:false},
  {id:'R1302',number:'1302',floor:'13',building:'Tower A',guest:'—',nationality:'—',status:'vacant',tv:'online',stay:'—',package:'Standard',dnd:false},
  {id:'R1303',number:'1303',floor:'13',building:'Tower A',guest:'Abdullah Salem',nationality:'Emirati',status:'occupied',tv:'online',stay:'19–22 Jul',package:'Premium',dnd:false},
  {id:'R1401',number:'1401',floor:'14',building:'Tower A',guest:'—',nationality:'—',status:'vacant',tv:'online',stay:'—',package:'Standard',dnd:false},
  {id:'R1402',number:'1402',floor:'14',building:'Tower A',guest:'Fatima Hassan',nationality:'Bahraini',status:'occupied',tv:'warning',stay:'21–25 Jul',package:'VIP',dnd:false},
  {id:'V101',number:'V101',floor:'1',building:'Villa Wing',guest:'—',nationality:'—',status:'vacant',tv:'online',stay:'—',package:'Villa',dnd:false}
 ],
 guests:[
  {id:'G1001',name:'Ahmed Mohammed',room:'1201',language:'Arabic',vip:'Gold',checkin:'21 Jul 15:10',checkout:'24 Jul 12:00',status:'in-house'},
  {id:'G1002',name:'Sara Khaled',room:'1203',language:'Arabic',vip:'Standard',checkin:'20 Jul 20:30',checkout:'23 Jul 12:00',status:'in-house'},
  {id:'G1003',name:'Mohammed Ali',room:'1301',language:'English',vip:'Platinum',checkin:'21 Jul 13:45',checkout:'26 Jul 12:00',status:'in-house'},
  {id:'G1004',name:'Abdullah Salem',room:'1303',language:'Arabic',vip:'Gold',checkin:'19 Jul 18:05',checkout:'22 Jul 12:00',status:'in-house'}
 ],
 devices:[
  {id:'TV1201',room:'1201',brand:'Samsung',model:'Q155Q7F',platform:'Tizen 9.0',ip:'192.168.20.31',mac:'3C:6A:9D:12:01:31',status:'online',app:'2.0.0',signal:98,last:'Now'},
  {id:'TV1202',room:'1202',brand:'Samsung',model:'Q155Q7F',platform:'Tizen 9.0',ip:'192.168.20.32',mac:'3C:6A:9D:12:01:32',status:'online',app:'2.0.0',signal:96,last:'1 min'},
  {id:'TV1203',room:'1203',brand:'Samsung',model:'Q155Q7F',platform:'Tizen 9.0',ip:'192.168.20.33',mac:'3C:6A:9D:12:01:33',status:'online',app:'2.0.0',signal:99,last:'Now'},
  {id:'TV1204',room:'1204',brand:'LG',model:'UT801C',platform:'webOS 24',ip:'192.168.20.34',mac:'A4:36:C7:12:04:34',status:'offline',app:'1.9.4',signal:0,last:'17 min'},
  {id:'TV1301',room:'1301',brand:'LG',model:'UT801C',platform:'webOS 24',ip:'192.168.20.41',mac:'A4:36:C7:13:01:41',status:'online',app:'2.0.0',signal:94,last:'Now'},
  {id:'TV1402',room:'1402',brand:'Samsung',model:'Q155Q7F',platform:'Tizen 9.0',ip:'192.168.20.52',mac:'3C:6A:9D:14:02:52',status:'warning',app:'1.8.2',signal:71,last:'4 min'}
 ],
 channels:[
  {id:'CH1',number:1,name:'Quran Kareem',name_ar:'القرآن الكريم',group:'Religious',source:'udp://239.10.1.1:5000',backup:'http://127.0.0.1/hls/1.m3u8',quality:'1080p',bitrate:'6.2 Mbps',epg:true,status:'online',uptime:99.99},
  {id:'CH2',number:2,name:'Sunnah',name_ar:'السنة النبوية',group:'Religious',source:'udp://239.10.1.2:5000',backup:'http://127.0.0.1/hls/2.m3u8',quality:'1080p',bitrate:'5.8 Mbps',epg:true,status:'online',uptime:99.98},
  {id:'CH3',number:3,name:'Saudi TV',name_ar:'السعودية',group:'Saudi',source:'udp://239.10.1.3:5000',backup:'http://127.0.0.1/hls/3.m3u8',quality:'1080p',bitrate:'7.1 Mbps',epg:true,status:'online',uptime:99.97},
  {id:'CH4',number:4,name:'Al Ekhbariya',name_ar:'الإخبارية',group:'News',source:'udp://239.10.1.4:5000',backup:'http://127.0.0.1/hls/4.m3u8',quality:'1080p',bitrate:'6.8 Mbps',epg:true,status:'online',uptime:99.95},
  {id:'CH5',number:5,name:'MBC 1',name_ar:'MBC 1',group:'Entertainment',source:'udp://239.10.2.1:5000',backup:'http://127.0.0.1/hls/5.m3u8',quality:'1080p',bitrate:'7.4 Mbps',epg:true,status:'online',uptime:99.91},
  {id:'CH6',number:6,name:'MBC Action',name_ar:'MBC أكشن',group:'Entertainment',source:'udp://239.10.2.2:5000',backup:'http://127.0.0.1/hls/6.m3u8',quality:'720p',bitrate:'3.1 Mbps',epg:false,status:'warning',uptime:96.4}
 ],
 packages:[
  {id:'PKG1',name:'Standard',rooms:62,channels:28,description:'Saudi, news and entertainment essentials',status:'published'},
  {id:'PKG2',name:'Premium',rooms:42,channels:54,description:'Full entertainment, sports and international channels',status:'published'},
  {id:'PKG3',name:'VIP',rooms:12,channels:72,description:'All channels, VOD and premium hotel services',status:'published'},
  {id:'PKG4',name:'Villa',rooms:4,channels:46,description:'Curated package for villa residences',status:'draft'}
 ],
 epg:[
  {channel:'Saudi TV',now:'Saudi News',next:'Cultural Dialogue',progress:62},
  {channel:'Al Ekhbariya',now:'Live Bulletin',next:'Markets Today',progress:41},
  {channel:'MBC 1',now:'Morning Show',next:'Drama Series',progress:78},
  {channel:'MBC Action',now:'Action Movie',next:'Top Gear',progress:33}
 ],
 requests:[
  {id:'REQ1042',service:'Extra amenities',room:'1203',guest:'Sara Khaled',department:'Housekeeping',priority:'normal',status:'new',created:'07:18',sla:'12 min'},
  {id:'REQ1041',service:'Room cleaning',room:'1301',guest:'Mohammed Ali',department:'Housekeeping',priority:'normal',status:'progress',created:'07:11',sla:'18 min'},
  {id:'REQ1040',service:'Air conditioning',room:'1204',guest:'—',department:'Engineering',priority:'high',status:'progress',created:'06:56',sla:'33 min'},
  {id:'REQ1039',service:'Luggage assistance',room:'1402',guest:'Fatima Hassan',department:'Bell Desk',priority:'normal',status:'done',created:'06:42',sla:'8 min'}
 ],
 signage:[
  {id:'SIG1',name:'Lobby Welcome Wall',zone:'Main Lobby',resolution:'3840×1080',playlist:'Brand & Events',status:'online',screens:3},
  {id:'SIG2',name:'Elevator Screens',zone:'Tower A',resolution:'1920×1080',playlist:'Hotel Offers',status:'online',screens:20},
  {id:'SIG3',name:'Restaurant Menu',zone:'Restaurant',resolution:'2160×3840',playlist:'Dining Menu',status:'warning',screens:2}
 ],
 integrations:[
  {id:'PMS',name:'Hotel PMS',vendor:'Oracle OPERA / Generic API',description:'Guest, room, check-in, checkout and billing synchronization',status:'ready',last:'Not configured'},
  {id:'WISI',name:'WISI Headend',vendor:'WISI OM / Tangram',description:'Channel sources, service discovery and stream health',status:'online',last:'21 Jul 10:42'},
  {id:'SAMSUNG',name:'Samsung Hospitality',vendor:'Tizen / LYNK',description:'Device registration, application launch and room mapping',status:'online',last:'21 Jul 10:41'},
  {id:'LG',name:'LG Hospitality',vendor:'webOS / Pro:Centric',description:'LG device fleet and guest application deployment',status:'ready',last:'Connector ready'},
  {id:'CAST',name:'Secure Casting',vendor:'Chromecast / AirPlay Gateway',description:'Guest pairing, isolation and automatic checkout reset',status:'ready',last:'Gateway required'},
  {id:'BILL',name:'Guest Billing',vendor:'PMS Posting API',description:'Post dining and service charges to guest folio',status:'ready',last:'PMS required'}
 ],
 users:[
  {id:'U1',name:'Hatem Elomda',email:'admin@hdb.local',role:'Super Administrator',scope:'All properties',status:'online'},
  {id:'U2',name:'Front Office',email:'reception@hdb.local',role:'Reception',scope:'HDB Riyadh Tower',status:'online'},
  {id:'U3',name:'Engineering Team',email:'engineering@hdb.local',role:'Engineering',scope:'Devices & Requests',status:'offline'},
  {id:'U4',name:'Content Manager',email:'content@hdb.local',role:'Content Editor',scope:'Channels & Experience',status:'online'}
 ],
 audit:[
  {event:'Channel order published',actor:'Content Manager',time:'10:42',type:'content'},
  {event:'TV1204 became offline',actor:'Device Monitor',time:'10:38',type:'alert'},
  {event:'Guest checked in to room 1301',actor:'PMS Connector',time:'09:56',type:'pms'},
  {event:'Welcome experience published',actor:'Hatem Elomda',time:'09:32',type:'experience'}
 ],
 experience:{hotel:'HDB Hospitality',welcome_ar:'أهلًا بك في هدب',welcome_en:'Welcome to HDB',subtitle_ar:'إقامة هادئة وتجربة رقمية صُممت لتكون كل خدمات الفندق بين يديك.',subtitle_en:'A calm stay with every hotel service within reach.',accent:'#d9b66f',background:'midnight',weather:true,prayer:true,bill:true,checkout:true,published_at:'21 Jul 09:32'},
 system:{api:99.99,middleware:99.97,headend:99.95,devices:96.4,storage:41,cpu:24,memory:52,streams:54}
};
var meta={
 command:['GLOBAL OVERVIEW','مركز القيادة','صورة لحظية لتشغيل الفندق وتجربة النزلاء','إجراء جديد'],
 operations:['HOTEL OPERATIONS','تشغيل الفندق','متابعة الإشغال والطلبات والأحداث التشغيلية','إنشاء مهمة'],
 properties:['PROPERTY STRUCTURE','المباني والأدوار','إدارة هيكل المنشأة من المبنى حتى الغرفة','إضافة مبنى'],
 rooms:['ROOMS & STAYS','الغرف والإقامات','إدارة حالات الغرف والتسكين وتجربة الإقامة','إضافة غرفة'],
 guests:['GUEST PROFILES','النزلاء','ملفات النزلاء واللغات والتفضيلات وسجل الإقامة','إضافة نزيل'],
 devices:['DEVICE FLEET','الأجهزة','إدارة شاشات Samsung وLG وأجهزة STB','ربط جهاز'],
 channels:['LIVE CONTENT','القنوات والمصادر','مصادر البث والنسخ الاحتياطية وحالة كل قناة','إضافة قناة'],
 packages:['PACKAGES & EPG','الباقات وEPG','تخصيص المحتوى حسب الغرفة وإدارة دليل البرامج','إنشاء باقة'],
 experience:['EXPERIENCE STUDIO','تجربة النزيل','تصميم ومعاينة ونشر واجهة التلفزيون','نشر التجربة'],
 requests:['GUEST SERVICES','الطلبات والخدمات','توجيه الطلبات ومتابعة SLA والأقسام','إنشاء طلب'],
 signage:['DIGITAL SIGNAGE','الشاشات الإعلانية','إدارة المناطق وقوائم التشغيل والحملات','إنشاء شاشة'],
 integrations:['INTEGRATION HUB','التكاملات','PMS وWISI وSamsung وLG والفوترة والكاستنج','إضافة تكامل'],
 reports:['ANALYTICS','التقارير','تقارير الإشغال والمحتوى والأجهزة وجودة الخدمة','تصدير تقرير'],
 users:['ACCESS CONTROL','المستخدمون والصلاحيات','أدوار دقيقة وسجل تدقيق ونطاق وصول','إضافة مستخدم'],
 system:['SYSTEM ADMINISTRATION','النظام','حالة الخادم والخدمات والنسخ الاحتياطي والتحديثات','فحص شامل']
};
function $(s,r){return(r||document).querySelector(s)}function $$(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function clone(v){return JSON.parse(JSON.stringify(v))}
function toast(t){var e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(function(){e.classList.remove('show')},2400)}
function status(v,label){return '<span class="status '+esc(v)+'">'+esc(label||v)+'</span>'}
function metric(title,value,sub,icon,delta,deltaClass){return '<article class="metric"><header><span>'+esc(title)+'</span><i>'+icon+'</i></header><strong>'+esc(value)+'</strong><footer><span>'+esc(sub)+'</span><b class="delta '+(deltaClass||'')+'">'+esc(delta||'')+'</b></footer></article>'}
function panel(title,kicker,body,span,extra){return '<section class="panel span-'+(span||12)+'"><div class="panel-head"><div><small>'+esc(kicker||'OVERVIEW')+'</small><h3>'+esc(title)+'</h3></div>'+(extra||'')+'</div><div class="panel-body">'+body+'</div></section>'}
function table(headers,rows){return '<div class="table-wrap"><table class="data-table"><thead><tr>'+headers.map(function(h){return'<th>'+h+'</th>'}).join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>'}
function match(obj){if(!searchTerm)return true;return JSON.stringify(obj).toLowerCase().indexOf(searchTerm)>-1}
function labelStatus(s){return{online:'متصل',offline:'غير متصل',warning:'تنبيه',occupied:'مشغولة',vacant:'شاغرة',service:'خدمة',published:'منشورة',draft:'مسودة',new:'جديد',progress:'قيد التنفيذ',done:'مكتمل',ready:'جاهز',failed:'خطأ','in-house':'داخل الفندق'}[s]||s}
function api(resource,options){options=options||{};var url=API+'?resource='+encodeURIComponent(resource||'state');return fetch(url,{method:options.method||'GET',headers:{'Content-Type':'application/json','X-HDB-Token':'change-me-production-token'},body:options.body?JSON.stringify(options.body):undefined,cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()})}
function load(){return api('state').then(function(x){state=x.data||x;localStorage.setItem('hdb_global_state',JSON.stringify(state));return state}).catch(function(){try{state=JSON.parse(localStorage.getItem('hdb_global_state')||'null')}catch(e){state=null}state=state||clone(seed);return state})}
function persist(){localStorage.setItem('hdb_global_state',JSON.stringify(state));return api('state',{method:'PUT',body:{data:state}}).catch(function(){return null})}
function setHeader(){var m=meta[view];$('#view-kicker').textContent=m[0];$('#view-title').textContent=m[1];$('#view-subtitle').textContent=m[2];$('#primary-btn').textContent=m[3]}
function render(){setHeader();var fn={command:renderCommand,operations:renderOperations,properties:renderProperties,rooms:renderRooms,guests:renderGuests,devices:renderDevices,channels:renderChannels,packages:renderPackages,experience:renderExperience,requests:renderRequests,signage:renderSignage,integrations:renderIntegrations,reports:renderReports,users:renderUsers,system:renderSystem}[view]||renderCommand;$('#workspace-content').innerHTML=fn();bindView()}
function renderCommand(){
 var occupied=state.rooms.filter(function(x){return x.status==='occupied'}).length,online=state.devices.filter(function(x){return x.status==='online'}).length,streams=state.channels.filter(function(x){return x.status==='online'}).length,open=state.requests.filter(function(x){return x.status!=='done'}).length;
 var hero='<div class="hero-strip"><div><small>HDB GLOBAL HOSPITALITY OS</small><h2>صباح الخير، التشغيل مستقر</h2><p>جميع الأنظمة الأساسية متصلة. يوجد تنبيه جهاز واحد وقناة تحتاج فحصًا.</p></div><div class="hero-status"><article><span>الإشغال</span><strong>'+Math.round(occupied/state.rooms.length*100)+'%</strong></article><article><span>رضا النزلاء</span><strong>4.8 / 5</strong></article><article><span>زمن الاستجابة</span><strong>11 دقيقة</strong></article></div></div>';
 var metrics='<div class="metrics">'+metric('الغرف المشغولة',occupied+'/'+state.rooms.length,'مقارنة بالأمس','▦','+4.2%','up')+metric('الأجهزة المتصلة',online+'/'+state.devices.length,'Samsung · LG · STB','▤','96.4%','up')+metric('القنوات المستقرة',streams+'/'+state.channels.length,'Uptime خلال 24 ساعة','▶','99.95%','up')+metric('طلبات مفتوحة',open,'تحتاج متابعة','◇','1 عاجل','warn')+'</div>';
 var chart='<div class="chart">'+[68,76,73,82,86,91,88,94,96,92,97,95].map(function(x,i){return'<div class="bar" style="height:'+x+'%"><i>'+x+'</i><span>'+(i+1)+'</span></div>'}).join('')+'</div>';
 var health='<div class="health-grid">'+[['Middleware','API & sessions',99],['WISI Headend','54 live services',98],['Device Manager','116 registered',96],['PMS Connector','Ready to configure',84]].map(function(x){return'<article class="health-card"><header><div><h4>'+x[0]+'</h4><small>'+x[1]+'</small></div>'+status(x[2]>95?'online':'warning',x[2]+'%')+'</header><div class="progress"><i style="width:'+x[2]+'%"></i></div></article>'}).join('')+'</div>';
 var req='<div class="timeline">'+state.requests.slice(0,4).map(function(r){return'<div class="timeline-item"><i>◇</i><span><b>'+esc(r.service)+' · '+esc(r.room)+'</b><small>'+esc(r.department)+' · SLA '+esc(r.sla)+'</small></span>'+status(r.status,labelStatus(r.status))+'</div>'}).join('')+'</div>';
 var audit='<div class="timeline">'+state.audit.map(function(a){return'<div class="timeline-item"><i>↻</i><span><b>'+esc(a.event)+'</b><small>'+esc(a.actor)+'</small></span><small>'+esc(a.time)+'</small></div>'}).join('')+'</div>';
 return hero+metrics+'<div class="grid">'+panel('جودة المنظومة','SYSTEM HEALTH',health,5,status('good','مستقر'))+panel('مؤشر التشغيل اليومي','OPERATIONS SCORE',chart,7,'<span class="status good">95 / 100</span>')+panel('الطلبات الأخيرة','GUEST REQUESTS',req,7,'<button class="btn secondary" data-jump="requests">عرض الكل</button>')+panel('آخر العمليات','AUDIT TRAIL',audit,5,'')+'</div>'
}
function renderOperations(){
 var rooms=state.rooms.map(function(r){return'<article class="room-card '+r.status+'" data-room="'+r.id+'"><header><strong>'+esc(r.number)+'</strong>'+status(r.status,labelStatus(r.status))+'</header><p>'+esc(r.guest)+' · TV '+labelStatus(r.tv)+'</p></article>'}).join('');
 var dept=[['Housekeeping',7,92],['Engineering',3,78],['Front Office',2,96],['Room Service',4,86]].map(function(x){return'<article class="health-card"><header><div><h4>'+x[0]+'</h4><small>'+x[1]+' active tasks</small></div><b>'+x[2]+'%</b></header><div class="progress"><i style="width:'+x[2]+'%"></i></div></article>'}).join('');
 return '<div class="metrics">'+metric('Arrivals today','18','12 completed','↘','6 pending','warn')+metric('Departures today','14','9 completed','↗','5 pending','warn')+metric('Rooms ready','93','Ready for sale','✓','+7','up')+metric('DND rooms','6','Do not disturb','—','Stable','')+'</div><div class="grid">'+panel('Live room board','ROOM OPERATIONS','<div class="room-map">'+rooms+'</div>',8,'<button class="btn secondary">Floor 12–14</button>')+panel('Department performance','SERVICE LEVELS','<div class="health-grid">'+dept+'</div>',4,'')+panel('Operational events','LIVE EVENT FEED',renderEventFeed(),12,'')+'</div>'
}
function renderEventFeed(){var items=[['PMS','Check-in completed for room 1301','09:56'],['Device','TV1204 lost heartbeat','10:38'],['Service','Engineering accepted REQ1040','10:41'],['Content','Channel lineup published to Premium package','10:42']];return '<div class="timeline">'+items.map(function(x){return'<div class="timeline-item"><i>'+x[0].charAt(0)+'</i><span><b>'+x[1]+'</b><small>'+x[0]+'</small></span><small>'+x[2]+'</small></div>'}).join('')+'</div>'}
function renderProperties(){var cards=state.buildings.map(function(b){return'<article class="package-card"><div class="card-top"><div class="entity"><div class="entity-icon">▦</div><span><b>'+esc(b.name)+'</b><small>'+b.floors+' floors · '+b.rooms+' rooms</small></span></div>'+status('online','Active')+'</div><p>Property: HDB Riyadh Tower. Central policies, channel packages and guest experience inherit from the property level.</p><div class="stats-line"><div><span>Floors</span><strong>'+b.floors+'</strong></div><div><span>Rooms</span><strong>'+b.rooms+'</strong></div></div></article>'}).join('');var floors=state.floors.map(function(f){return'<tr><td><div class="entity"><div class="entity-icon">'+f.number+'</div><span><b>Floor '+f.number+'</b><small>'+esc(f.building_id)+'</small></span></div></td><td>'+f.rooms+'</td><td>'+state.rooms.filter(function(r){return r.floor===f.number&&r.status==='occupied'}).length+'</td><td>'+status('online','Inherited')+'</td><td><button class="icon-btn">⋯</button></td></tr>'}).join('');return '<div class="toolbar"><div class="filters"><input placeholder="Search buildings or floors"><select><option>All buildings</option><option>Tower A</option><option>Villa Wing</option></select></div><button class="btn primary" data-create="building">Add building</button></div><div class="card-grid">'+cards+'</div><div class="grid">'+panel('Floors and inherited policies','FLOOR DIRECTORY',table(['Floor','Rooms','Occupied','Policy',''],floors),12,'')+'</div>'}
function renderRooms(){var rows=state.rooms.filter(match).map(function(r){return'<tr><td><div class="entity"><div class="entity-icon">'+esc(r.number)+'</div><span><b>Room '+esc(r.number)+'</b><small>'+esc(r.building)+' · Floor '+esc(r.floor)+'</small></span></div></td><td>'+esc(r.guest)+'</td><td>'+status(r.status,labelStatus(r.status))+'</td><td>'+status(r.tv,labelStatus(r.tv))+'</td><td>'+esc(r.package)+'</td><td>'+esc(r.stay)+'</td><td><div class="actions"><button class="icon-btn" data-edit="room" data-id="'+r.id+'">✎</button><button class="icon-btn">⋯</button></div></td></tr>'}).join('');return '<div class="toolbar"><div class="filters"><input id="room-filter-search" placeholder="Search room, guest or floor"><select><option>All statuses</option><option>Occupied</option><option>Vacant</option><option>Service</option></select><select><option>All buildings</option><option>Tower A</option><option>Villa Wing</option></select></div><button class="btn primary" data-create="room">Add room</button></div>'+panel('Rooms and active stays','ROOM DIRECTORY',table(['Room','Guest','Room status','TV','Package','Stay',''],rows||'<tr><td colspan="7" class="empty">No results</td></tr>'),12,'<span class="status good">'+state.rooms.length+' rooms</span>')}
function renderGuests(){var rows=state.guests.filter(match).map(function(g){return'<tr><td><div class="entity"><div class="entity-icon">♙</div><span><b>'+esc(g.name)+'</b><small>'+esc(g.id)+'</small></span></div></td><td>'+esc(g.room)+'</td><td>'+esc(g.language)+'</td><td>'+esc(g.vip)+'</td><td>'+esc(g.checkin)+'</td><td>'+esc(g.checkout)+'</td><td>'+status(g.status,labelStatus(g.status))+'</td><td><button class="icon-btn">⋯</button></td></tr>'}).join('');return '<div class="toolbar"><div class="filters"><input placeholder="Search guest or room"><select><option>In-house guests</option><option>Arrivals</option><option>Departures</option></select></div><button class="btn primary" data-create="guest">Add guest</button></div>'+panel('Guest profiles and stay preferences','GUEST DIRECTORY',table(['Guest','Room','Language','VIP','Check-in','Checkout','Status',''],rows),12,'')}
function renderDevices(){var cards=state.devices.filter(match).map(function(d){return'<article class="device-card"><div class="card-top"><div class="entity"><div class="entity-icon">▤</div><span><b>'+esc(d.id)+'</b><small>Room '+esc(d.room)+'</small></span></div>'+status(d.status,labelStatus(d.status))+'</div><div class="device-screen">'+esc(d.brand)+'</div><h3>'+esc(d.brand+' '+d.model)+'</h3><p>'+esc(d.platform)+' · '+esc(d.ip)+'<br>'+esc(d.mac)+'</p><div class="stats-line"><div><span>App version</span><strong>'+esc(d.app)+'</strong></div><div><span>Signal</span><strong>'+esc(d.signal)+'%</strong></div></div><div class="actions" style="margin-top:12px"><button class="btn secondary" data-command="restart" data-id="'+d.id+'">Restart</button><button class="btn secondary" data-command="sync" data-id="'+d.id+'">Sync</button></div></article>'}).join('');return '<div class="toolbar"><div class="filters"><input placeholder="Search room, IP, MAC or model"><select><option>All platforms</option><option>Samsung Tizen</option><option>LG webOS</option><option>STB</option></select><select><option>All statuses</option><option>Online</option><option>Warning</option><option>Offline</option></select></div><div><button class="btn secondary" data-action="discover">Discover devices</button> <button class="btn primary" data-create="device">Register device</button></div></div><div class="card-grid">'+cards+'</div>'}
function renderChannels(){var rows=state.channels.filter(match).sort(function(a,b){return a.number-b.number}).map(function(c){return'<tr><td><strong>'+c.number+'</strong></td><td><div class="entity"><div class="entity-icon">▶</div><span><b>'+esc(c.name_ar)+'</b><small>'+esc(c.name)+'</small></span></div></td><td>'+esc(c.group)+'</td><td><span title="'+esc(c.source)+'">'+esc(c.source)+'</span><small style="display:block;color:var(--muted);margin-top:3px">Backup configured</small></td><td>'+esc(c.quality)+' · '+esc(c.bitrate)+'</td><td>'+status(c.status,labelStatus(c.status))+'</td><td>'+esc(c.uptime)+'%</td><td><div class="actions"><button class="icon-btn" data-edit="channel" data-id="'+c.id+'">✎</button><button class="icon-btn">⋯</button></div></td></tr>'}).join('');return '<div class="toolbar"><div class="filters"><input placeholder="Search channel, source or group"><select><option>All groups</option><option>Religious</option><option>Saudi</option><option>News</option><option>Entertainment</option></select></div><div><button class="btn secondary" data-action="scan">Scan sources</button> <button class="btn primary" data-create="channel">Add channel</button></div></div>'+panel('Live channels and source redundancy','CHANNEL OPERATIONS',table(['#','Channel','Group','Primary source','Quality','Status','Uptime',''],rows),12,'<span class="status good">'+state.channels.length+' services</span>')}
function renderPackages(){var cards=state.packages.map(function(p){return'<article class="package-card"><div class="card-top"><div class="entity"><div class="entity-icon">◈</div><span><b>'+esc(p.name)+'</b><small>'+p.channels+' channels</small></span></div>'+status(p.status,labelStatus(p.status))+'</div><p>'+esc(p.description)+'</p><div class="stats-line"><div><span>Assigned rooms</span><strong>'+p.rooms+'</strong></div><div><span>Channels</span><strong>'+p.channels+'</strong></div></div><div class="actions" style="margin-top:12px"><button class="btn secondary">Edit lineup</button><button class="btn secondary">Assign</button></div></article>'}).join('');var epg=state.epg.map(function(e){return'<div class="health-card"><header><div><h4>'+esc(e.channel)+'</h4><small>Now: '+esc(e.now)+'</small></div><b>'+e.progress+'%</b></header><div class="progress"><i style="width:'+e.progress+'%"></i></div><small style="display:block;margin-top:8px;color:var(--muted)">Next: '+esc(e.next)+'</small></div>'}).join('');return '<div class="toolbar"><div class="filters"><select><option>All packages</option></select></div><div><button class="btn secondary">Import XMLTV</button> <button class="btn primary" data-create="package">Create package</button></div></div><div class="card-grid">'+cards+'</div><div class="grid">'+panel('Live electronic program guide','EPG NOW & NEXT','<div class="health-grid">'+epg+'</div>',12,'<span class="status good">XMLTV synced</span>')+'</div>'}
function renderExperience(){var e=state.experience;return '<div class="experience-layout"><section class="panel editor"><div class="panel-head" style="margin:-18px -18px 18px"><div><small>EXPERIENCE STUDIO</small><h3>Guest TV editor</h3></div>'+status('published','Published')+'</div><label>Hotel name<input id="exp-hotel" value="'+esc(e.hotel)+'"></label><label>Arabic welcome<input id="exp-welcome-ar" value="'+esc(e.welcome_ar)+'"></label><label>English welcome<input id="exp-welcome-en" value="'+esc(e.welcome_en)+'"></label><label>Arabic subtitle<textarea id="exp-sub-ar">'+esc(e.subtitle_ar)+'</textarea></label><div class="editor-row"><label>Accent color<input id="exp-color" type="color" value="'+esc(e.accent)+'"></label><label>Background<select id="exp-bg"><option value="midnight">Midnight luxury</option><option value="sand">Desert gold</option><option value="light">Modern light</option></select></label></div><div class="editor-row"><label>Weather<select><option>Enabled</option><option>Disabled</option></select></label><label>Prayer times<select><option>Enabled</option><option>Disabled</option></select></label></div><div class="actions"><button class="btn secondary" id="preview-exp">Update preview</button><button class="btn primary" id="publish-exp">Publish to property</button></div><p style="color:var(--muted);font-size:8px;margin-top:14px">Last published: '+esc(e.published_at)+'</p></section><section class="tv-stage"><div class="tv-frame"><div class="tv-screen" id="tv-preview"><small>HDB PERSONALIZED STAY</small><h2 id="preview-welcome">'+esc(e.welcome_ar)+'</h2><p id="preview-sub">'+esc(e.subtitle_ar)+'</p><button>الدخول إلى خدمات الفندق</button></div></div></section></div>'}
function renderRequests(){var rows=state.requests.filter(match).map(function(r){var action=r.status==='new'?'<button class="btn primary" data-next-request="'+r.id+'">Accept</button>':r.status==='progress'?'<button class="btn success" data-next-request="'+r.id+'">Complete</button>':'<span class="status done">Closed</span>';return'<tr><td><strong>'+esc(r.id)+'</strong></td><td>'+esc(r.service)+'</td><td>'+esc(r.room)+'</td><td>'+esc(r.guest)+'</td><td>'+esc(r.department)+'</td><td>'+(r.priority==='high'?status('warning','High'):status('good','Normal'))+'</td><td>'+status(r.status,labelStatus(r.status))+'</td><td>'+esc(r.sla)+'</td><td>'+action+'</td></tr>'}).join('');return '<div class="metrics">'+metric('Requests today',24,'Across all departments','◇','+8%','up')+metric('Open',state.requests.filter(function(x){return x.status!=='done'}).length,'Needs attention','!','1 high','warn')+metric('Average SLA','11 min','Target 15 minutes','⌁','-3 min','up')+metric('Guest rating','4.8','Service satisfaction','★','+0.2','up')+'</div><div class="grid">'+panel('Guest request queue','SERVICE COMMAND CENTER',table(['ID','Service','Room','Guest','Department','Priority','Status','SLA','Action'],rows),12,'<button class="btn secondary">Department board</button>')+'</div>'}
function renderSignage(){var cards=state.signage.map(function(s){return'<article class="device-card"><div class="card-top"><div class="entity"><div class="entity-icon">▧</div><span><b>'+esc(s.name)+'</b><small>'+esc(s.zone)+'</small></span></div>'+status(s.status,labelStatus(s.status))+'</div><div class="device-screen">SIGNAGE</div><h3>'+esc(s.playlist)+'</h3><p>'+esc(s.resolution)+' · '+s.screens+' screens</p><div class="actions"><button class="btn secondary">Open playlist</button><button class="btn secondary">Preview</button></div></article>'}).join('');return '<div class="toolbar"><div class="filters"><input placeholder="Search screen, zone or playlist"><select><option>All zones</option><option>Lobby</option><option>Elevators</option><option>Restaurant</option></select></div><button class="btn primary" data-create="signage">Create signage zone</button></div><div class="card-grid">'+cards+'</div>'}
function renderIntegrations(){var cards=state.integrations.map(function(i){return'<article class="integration-card"><div class="card-top"><div class="integration-logo">'+esc(i.id)+'</div>'+status(i.status,i.status==='online'?'Connected':'Ready')+'</div><h3 style="margin-top:14px">'+esc(i.name)+'</h3><p><b style="color:#c8d4e1">'+esc(i.vendor)+'</b><br>'+esc(i.description)+'</p><footer><small style="color:var(--muted)">'+esc(i.last)+'</small><button class="btn secondary" data-integration="'+i.id+'">Configure</button></footer></article>'}).join('');return '<div class="hero-strip"><div><small>OPEN INTEGRATION ARCHITECTURE</small><h2>Connect every hotel system</h2><p>REST APIs, event webhooks, scheduled synchronization and connector health monitoring.</p></div><div class="hero-status"><article><span>Connected</span><strong>3</strong></article><article><span>Ready</span><strong>3</strong></article><article><span>Errors</span><strong>0</strong></article></div></div><div class="card-grid" style="margin-top:14px">'+cards+'</div>'}
function renderReports(){var reports=[['Daily operations report','Occupancy, arrivals, departures, requests and device health'],['Channel performance','Uptime, bitrate, failover and viewing trends'],['Device fleet report','Online ratio, versions, incidents and update compliance'],['Guest services SLA','Response time by department and service category'],['Content engagement','Top channels, menu sections and message interactions'],['Audit and compliance','User actions, configuration changes and security events']];var cards=reports.map(function(r){return'<article class="report-card"><h3>'+r[0]+'</h3><p>'+r[1]+'</p><button class="btn secondary" data-report="'+r[0]+'">Generate report</button></article>'}).join('');return '<div class="metrics">'+metric('TV sessions','1,284','Last 7 days','▶','+12%','up')+metric('Average watch time','74 min','Per occupied room','⌁','+6 min','up')+metric('Service requests','186','Last 30 days','◇','-9%','up')+metric('System uptime','99.97%','Last 90 days','✓','SLA met','up')+'</div><div class="grid">'+panel('Available reports','REPORT LIBRARY','<div class="report-cards">'+cards+'</div>',12,'<button class="btn primary">Schedule report</button>')+'</div>'}
function renderUsers(){var cards=state.users.map(function(u){return'<article class="user-card"><div class="card-top"><div class="entity"><div class="entity-icon">♙</div><span><b>'+esc(u.name)+'</b><small>'+esc(u.email)+'</small></span></div>'+status(u.status,labelStatus(u.status))+'</div><p><b style="color:#d5dfeb">'+esc(u.role)+'</b><br>'+esc(u.scope)+'</p><div class="actions"><button class="btn secondary">Permissions</button><button class="btn secondary">Audit</button></div></article>'}).join('');return '<div class="toolbar"><div class="filters"><input placeholder="Search users or roles"><select><option>All roles</option><option>Administrator</option><option>Reception</option><option>Engineering</option><option>Content</option></select></div><button class="btn primary" data-create="user">Add user</button></div><div class="card-grid">'+cards+'</div>'}
function renderSystem(){var s=state.system;var health='<div class="health-grid">'+[['API Gateway',s.api],['Middleware',s.middleware],['WISI Headend',s.headend],['Device Fleet',s.devices]].map(function(x){return'<article class="health-card"><header><div><h4>'+x[0]+'</h4><small>Last 24 hours</small></div>'+status(x[1]>98?'online':'warning',x[1]+'%')+'</header><div class="progress"><i style="width:'+x[1]+'%"></i></div></article>'}).join('')+'</div>';var resources='<div class="health-grid">'+[['CPU usage',s.cpu],['Memory usage',s.memory],['Storage used',s.storage],['Active streams',Math.round(s.streams/72*100)]].map(function(x){return'<article class="health-card"><header><div><h4>'+x[0]+'</h4><small>Current utilization</small></div><b>'+x[1]+'%</b></header><div class="progress"><i style="width:'+x[1]+'%"></i></div></article>'}).join('')+'</div>';return '<div class="metrics">'+metric('Core version',state.meta.version,'Production channel','⚙','Current','up')+metric('API latency','42 ms','Internal network','⌁','Excellent','up')+metric('Last backup','Today 03:00','Encrypted local backup','▧','Successful','up')+metric('Security events','0','Last 24 hours','✓','Clear','up')+'</div><div class="grid">'+panel('Service availability','CORE SERVICES',health,6,status('good','Operational'))+panel('Server resources','INFRASTRUCTURE',resources,6,'')+panel('Audit trail','SECURITY & CHANGES','<div class="timeline">'+state.audit.map(function(a){return'<div class="timeline-item"><i>↻</i><span><b>'+esc(a.event)+'</b><small>'+esc(a.actor)+'</small></span><small>'+esc(a.time)+'</small></div>'}).join('')+'</div>',7,'')+panel('Maintenance controls','ADMINISTRATION','<div class="report-cards"><article class="report-card"><h3>Backup now</h3><p>Create an encrypted configuration and data snapshot.</p><button class="btn secondary" data-action="backup">Run backup</button></article><article class="report-card"><h3>Health diagnostics</h3><p>Test storage, API, streams and device communication.</p><button class="btn secondary" data-action="diagnostics">Run diagnostics</button></article><article class="report-card"><h3>Software update</h3><p>Check the configured release channel for updates.</p><button class="btn secondary" data-action="update">Check updates</button></article></div>',5,'')+'</div>'}
function openModal(type,id){var title={room:'Room',guest:'Guest',device:'Device',channel:'Channel',package:'Package',building:'Building',signage:'Signage zone',user:'User'}[type]||'Item';$('#modal-kicker').textContent=id?'EDIT':'CREATE';$('#modal-title').textContent=(id?'Edit ':'Add ')+title;var fields={room:[['Room number','number'],['Floor','floor'],['Building','building'],['Package','package']],guest:[['Guest name','name'],['Room','room'],['Language','language'],['VIP tier','vip']],device:[['Device ID','id'],['Room','room'],['Brand','brand'],['IP address','ip']],channel:[['Channel number','number'],['Arabic name','name_ar'],['English name','name'],['Primary source','source']],package:[['Package name','name'],['Description','description'],['Channel count','channels']],building:[['Building name','name'],['Number of floors','floors'],['Number of rooms','rooms']],signage:[['Zone name','name'],['Location','zone'],['Resolution','resolution'],['Playlist','playlist']],user:[['Full name','name'],['Email','email'],['Role','role'],['Scope','scope']]}[type]||[['Name','name']];$('#modal-fields').innerHTML=fields.map(function(f){return'<label>'+f[0]+'<input name="'+f[1]+'" required></label>'}).join('');$('#modal-form').dataset.type=type;$('#modal-form').dataset.id=id||'';$('#global-modal').showModal()}
function saveModal(){var form=$('#modal-form'),type=form.dataset.type,id=form.dataset.id,data={};new FormData(form).forEach(function(v,k){data[k]=v});var map={room:'rooms',guest:'guests',device:'devices',channel:'channels',package:'packages',building:'buildings',signage:'signage',user:'users'},key=map[type]||type+'s';state[key]=state[key]||[];if(id){var item=state[key].filter(function(x){return x.id===id})[0];if(item)Object.assign(item,data)}else{data.id=(type||'item').toUpperCase()+Date.now();if(type==='room'){data.status='vacant';data.tv='offline';data.guest='—';data.stay='—'}if(type==='channel'){data.status='online';data.quality='1080p';data.uptime=100}if(type==='device'){data.status='online';data.model='Unknown';data.platform='Web';data.signal=100;data.app='2.0.0'}if(type==='user')data.status='offline';if(type==='package'){data.status='draft';data.rooms=0}if(type==='signage'){data.status='online';data.screens=1}state[key].push(data)}persist();toast(titleCase(type)+' saved');setTimeout(render,100)}
function titleCase(s){return String(s||'item').charAt(0).toUpperCase()+String(s||'item').slice(1)}
function bindView(){
 $$('[data-jump]').forEach(function(b){b.onclick=function(){switchView(b.dataset.jump)}});
 $$('[data-create]').forEach(function(b){b.onclick=function(){openModal(b.dataset.create)}});
 $$('[data-edit]').forEach(function(b){b.onclick=function(){openModal(b.dataset.edit,b.dataset.id)}});
 $$('[data-command]').forEach(function(b){b.onclick=function(){toast(b.dataset.command+' command sent to '+b.dataset.id)}});
 $$('[data-next-request]').forEach(function(b){b.onclick=function(){var r=state.requests.filter(function(x){return x.id===b.dataset.nextRequest})[0];if(!r)return;r.status=r.status==='new'?'progress':'done';persist();toast('Request '+r.id+' updated');render()}});
 $$('[data-action]').forEach(function(b){b.onclick=function(){var a=b.dataset.action;if(a==='discover'||a==='scan'||a==='diagnostics'){toast('Operation started — results will appear shortly')}else if(a==='backup'){toast('Encrypted backup created successfully')}else if(a==='update'){toast('Global Core 2.0 is current')}}});
 $$('[data-report]').forEach(function(b){b.onclick=function(){toast(b.dataset.report+' generated')}});
 $$('[data-integration]').forEach(function(b){b.onclick=function(){toast('Opening '+b.dataset.integration+' connector configuration')}});
 var p=$('#preview-exp');if(p)p.onclick=updatePreview;var pub=$('#publish-exp');if(pub)pub.onclick=function(){updatePreview();state.experience.hotel=$('#exp-hotel').value;state.experience.welcome_ar=$('#exp-welcome-ar').value;state.experience.welcome_en=$('#exp-welcome-en').value;state.experience.subtitle_ar=$('#exp-sub-ar').value;state.experience.accent=$('#exp-color').value;state.experience.published_at=new Date().toLocaleString();persist();toast('Guest experience published to property')}
}
function updatePreview(){var screen=$('#tv-preview');if(!screen)return;$('#preview-welcome').textContent=$('#exp-welcome-ar').value;$('#preview-sub').textContent=$('#exp-sub-ar').value;screen.style.setProperty('--preview-accent',$('#exp-color').value);screen.querySelector('button').style.background=$('#exp-color').value;toast('Preview updated')}
function switchView(v){view=v;$$('.nav-item').forEach(function(n){n.classList.toggle('active',n.dataset.view===v)});render()}
function bindShell(){
 $$('#main-nav .nav-item').forEach(function(b){b.onclick=function(){switchView(b.dataset.view)}});
 $('#global-search').oninput=function(){searchTerm=this.value.trim().toLowerCase();render()};
 $('#sync-btn').onclick=function(){toast('Synchronizing PMS, devices and channel sources');load().then(render)};
 $('#primary-btn').onclick=function(){var map={properties:'building',rooms:'room',guests:'guest',devices:'device',channels:'channel',packages:'package',signage:'signage',users:'user'};if(view==='experience'){var b=$('#publish-exp');if(b)b.click();else toast('Open Experience Studio')}else if(map[view])openModal(map[view]);else toast(meta[view][3]+' started')};
 $('#modal-form').addEventListener('submit',function(e){if(e.submitter&&e.submitter.value==='default'){e.preventDefault();saveModal();$('#global-modal').close()}})
}
load().then(function(){bindShell();render()});
})();
